config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'profile', to: 'users#show', as: 'user'
  post 'add_balance', to: 'users#add_balance'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_commit :add_eth_address, on: :create

  def eth_balance
    client = Ethereum::HttpClient.new('http://localhost:8545')
    balance = client.eth_get_balance(self.eth_address)
    # ... convert balance to desired format and return it ...
  end

  private

  def add_eth_address
    EthAddressWorker.perform_async(self.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :add_balance]

  def show
    @user = current_user
    @balance = @user.eth_balance["result"]
  end

  def add_balance
    EthTransferWorker.perform_async(current_user.id)
    redirect_to "/profile", :flash => { notice: 'Balance addition has been queued.' }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityFantasy16</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User Details</h1>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>ETH Address:</strong>
  <%= @user.eth_address %>
</p>

<p>
  <strong>ETH Balance:</strong>
  <%= @balance %>
</p>

<%= button_to 'Add Balance', add_balance_path, method: :post %>

<%= link_to 'Log out', destroy_user_session_path, method: :get %>

<!-- Display flash messages -->
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>